import type { Recipe } from "./types"

export const recipesData: Recipe[] = [
  {
    id: "1",
    name: "Phở Bò Hà Nội",
    description: "Món phở truyền thống của Hà Nội với nước dùng trong, thơm ngon từ xương bò hầm nhiều giờ",
    image: "/vietnamese-beef-pho-bowl-with-herbs.jpg",
    category: "món chính",
    cuisine: "Bắc",
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    difficulty: "Trung bình",
    ingredients: [
      { name: "Xương bò", amount: "1", unit: "kg" },
      { name: "Thịt bò", amount: "500", unit: "g" },
      { name: "Bánh phở", amount: "500", unit: "g" },
      { name: "Hành tây", amount: "2", unit: "củ" },
      { name: "Gừng", amount: "50", unit: "g" },
      { name: "Hồi", amount: "3", unit: "cái" },
      { name: "Quế", amount: "2", unit: "que" },
      { name: "Hành lá", amount: "1", unit: "bó" },
      { name: "Ngò gai", amount: "1", unit: "bó" },
      { name: "Giá đỗ", amount: "200", unit: "g" },
    ],
    instructions: [
      "Rửa sạch xương bò, chần qua nước sôi để loại bỏ tạp chất",
      "Nướng hành tây và gừng trên bếp cho thơm",
      "Cho xương bò vào nồi, đổ nước ngập, thêm hành tây, gừng đã nướng",
      "Hầm xương trong 3 giờ, vớt bọt thường xuyên",
      "Rang hồi, quế cho thơm rồi cho vào nồi nước dùng",
      "Luộc thịt bò riêng, thái lát mỏng",
      "Trụng bánh phở qua nước sôi",
      "Xếp bánh phở vào tô, cho thịt bò lên trên, chan nước dùng nóng",
      "Ăn kèm với hành lá, ngò gai, giá đỗ và chanh ớt",
    ],
    nutrition: {
      calories: 450,
      protein: 35,
      carbs: 55,
      fat: 12,
    },
    tags: ["truyền thống", "bữa sáng", "món nước", "phổ biến"],
  },
  {
    id: "2",
    name: "Cơm Tấm Sườn Nướng",
    description: "Món ăn đặc trưng miền Nam với cơm tấm thơm, sườn nướng đậm đà",
    image: "/vietnamese-broken-rice-with-grilled-pork.jpg",
    category: "món chính",
    cuisine: "Nam",
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "Dễ",
    ingredients: [
      { name: "Cơm tấm", amount: "300", unit: "g" },
      { name: "Sườn non", amount: "400", unit: "g" },
      { name: "Nước mắm", amount: "3", unit: "thìa" },
      { name: "Đường", amount: "2", unit: "thìa" },
      { name: "Tỏi băm", amount: "2", unit: "tép" },
      { name: "Sả", amount: "2", unit: "cây" },
      { name: "Trứng", amount: "2", unit: "quả" },
      { name: "Dưa leo", amount: "1", unit: "trái" },
      { name: "Cà chua", amount: "2", unit: "quả" },
    ],
    instructions: [
      "Ướp sườn với nước mắm, đường, tỏi băm, sả băm trong 2 giờ",
      "Nướng sườn trên than hoa hoặc lò nướng đến khi chín vàng",
      "Chiên trứng ốp la",
      "Nấu cơm tấm",
      "Xếp cơm ra đĩa, cho sườn nướng, trứng ốp la lên trên",
      "Ăn kèm với dưa leo, cà chua và nước mắm pha",
    ],
    nutrition: {
      calories: 650,
      protein: 40,
      carbs: 70,
      fat: 22,
    },
    tags: ["miền Nam", "bữa trưa", "nướng", "phổ biến"],
  },
  {
    id: "3",
    name: "Bún Chả Hà Nội",
    description: "Món bún chả truyền thống với thịt nướng thơm lừng, nước mắm chua ngọt",
    image: "/vietnamese-bun-cha-with-grilled-pork-and-noodles.jpg",
    category: "món chính",
    cuisine: "Bắc",
    prepTime: 30,
    cookTime: 20,
    servings: 4,
    difficulty: "Trung bình",
    ingredients: [
      { name: "Thịt ba chỉ", amount: "500", unit: "g" },
      { name: "Thịt nạc vai", amount: "300", unit: "g" },
      { name: "Bún tươi", amount: "500", unit: "g" },
      { name: "Nước mắm", amount: "100", unit: "ml" },
      { name: "Đường", amount: "3", unit: "thìa" },
      { name: "Tỏi", amount: "5", unit: "tép" },
      { name: "Giấm", amount: "2", unit: "thìa" },
      { name: "Rau thơm", amount: "1", unit: "bó" },
    ],
    instructions: [
      "Ướp thịt với nước mắm, đường, tỏi băm trong 1 giờ",
      "Thịt ba chỉ thái miếng vừa ăn, thịt nạc làm thành chả viên",
      "Nướng thịt trên bếp than cho thơm",
      "Pha nước mắm chua ngọt với đường, giấm, tỏi ớt",
      "Trụng bún qua nước sôi",
      "Bày bún ra tô, cho thịt nướng vào bát nước mắm",
      "Ăn kèm với rau thơm đa dạng",
    ],
    nutrition: {
      calories: 580,
      protein: 38,
      carbs: 62,
      fat: 18,
    },
    tags: ["truyền thống", "bữa trưa", "nướng", "Hà Nội"],
  },
  {
    id: "4",
    name: "Canh Chua Cá",
    description: "Món canh chua đặc trưng miền Nam với cá tươi, rau thơm và vị chua thanh mát",
    image: "/vietnamese-sour-fish-soup-with-vegetables.jpg",
    category: "canh",
    cuisine: "Nam",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Dễ",
    ingredients: [
      { name: "Cá lóc", amount: "500", unit: "g" },
      { name: "Me", amount: "50", unit: "g" },
      { name: "Cà chua", amount: "3", unit: "quả" },
      { name: "Dứa", amount: "200", unit: "g" },
      { name: "Đậu bắp", amount: "100", unit: "g" },
      { name: "Giá đỗ", amount: "100", unit: "g" },
      { name: "Rau muống", amount: "1", unit: "bó" },
      { name: "Ngò gai", amount: "50", unit: "g" },
    ],
    instructions: [
      "Rửa sạch cá, cắt khúc vừa ăn",
      "Ngâm me với nước ấm, lọc lấy nước",
      "Đun sôi nước, cho nước me, cà chua, dứa vào",
      "Thêm đậu bắp, nêm nếm gia vị",
      "Cho cá vào nấu chín",
      "Cuối cùng cho giá đỗ, rau muống, ngò gai",
      "Tắt bếp, ăn nóng với cơm",
    ],
    nutrition: {
      calories: 180,
      protein: 22,
      carbs: 15,
      fat: 4,
    },
    tags: ["canh", "miền Nam", "chua", "nhẹ nhàng"],
  },
  {
    id: "5",
    name: "Gỏi Cuốn Tôm Thịt",
    description: "Món gỏi cuốn tươi mát với tôm, thịt và rau sống, chấm nước mắm chua ngọt",
    image: "/vietnamese-fresh-spring-rolls-with-shrimp-and-pork.jpg",
    category: "món phụ",
    cuisine: "Nam",
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: "Dễ",
    ingredients: [
      { name: "Bánh tráng", amount: "20", unit: "tờ" },
      { name: "Tôm", amount: "300", unit: "g" },
      { name: "Thịt ba chỉ", amount: "200", unit: "g" },
      { name: "Bún tươi", amount: "200", unit: "g" },
      { name: "Xà lách", amount: "1", unit: "bó" },
      { name: "Rau thơm", amount: "1", unit: "bó" },
      { name: "Dưa leo", amount: "1", unit: "trái" },
    ],
    instructions: [
      "Luộc tôm và thịt, để nguội",
      "Trụng bún qua nước sôi",
      "Rửa sạch rau, để ráo nước",
      "Nhúng bánh tráng qua nước ấm cho mềm",
      "Đặt rau, bún, tôm, thịt lên bánh tráng rồi cuốn tròn",
      "Ăn kèm với nước mắm pha hoặc tương đậu phộng",
    ],
    nutrition: {
      calories: 220,
      protein: 18,
      carbs: 28,
      fat: 5,
    },
    tags: ["khai vị", "tươi mát", "lành mạnh", "dễ làm"],
  },
  {
    id: "6",
    name: "Bò Kho",
    description: "Món bò kho đậm đà, thơm ngon với nước sốt cà chua và gia vị đặc trưng",
    image: "/vietnamese-beef-stew-with-carrots.jpg",
    category: "món chính",
    cuisine: "Nam",
    prepTime: 20,
    cookTime: 90,
    servings: 4,
    difficulty: "Trung bình",
    ingredients: [
      { name: "Thịt bò", amount: "800", unit: "g" },
      { name: "Cà rốt", amount: "3", unit: "củ" },
      { name: "Khoai tây", amount: "2", unit: "củ" },
      { name: "Sả", amount: "3", unit: "cây" },
      { name: "Tỏi", amount: "5", unit: "tép" },
      { name: "Ớt", amount: "2", unit: "trái" },
      { name: "Cà chua", amount: "3", unit: "quả" },
      { name: "Bột cà ri", amount: "2", unit: "thìa" },
    ],
    instructions: [
      "Thái thịt bò thành miếng vừa ăn",
      "Ướp thịt với sả, tỏi, ớt, bột cà ri trong 30 phút",
      "Phi thơm sả, tỏi, cho thịt vào xào",
      "Thêm cà chua, nước, đun sôi",
      "Hầm nhỏ lửa trong 1 giờ",
      "Thêm cà rốt, khoai tây, nấu thêm 30 phút",
      "Nêm nếm gia vị cho vừa khẩu vị",
      "Ăn với bánh mì hoặc cơm",
    ],
    nutrition: {
      calories: 420,
      protein: 42,
      carbs: 28,
      fat: 16,
    },
    tags: ["món kho", "đậm đà", "bữa trưa", "bữa tối"],
  },
  {
    id: "7",
    name: "Chè Đậu Xanh",
    description: "Món chè truyền thống với đậu xanh bùi, nước cốt dừa thơm béo",
    image: "/vietnamese-mung-bean-sweet-soup-with-coconut-milk.jpg",
    category: "món tráng miệng",
    cuisine: "Bắc",
    prepTime: 10,
    cookTime: 40,
    servings: 4,
    difficulty: "Dễ",
    ingredients: [
      { name: "Đậu xanh", amount: "300", unit: "g" },
      { name: "Đường", amount: "150", unit: "g" },
      { name: "Nước cốt dừa", amount: "200", unit: "ml" },
      { name: "Lá dứa", amount: "2", unit: "lá" },
      { name: "Muối", amount: "1/4", unit: "thìa" },
    ],
    instructions: [
      "Ngâm đậu xanh 2 giờ, rửa sạch",
      "Nấu đậu xanh với nước và lá dứa đến khi mềm",
      "Thêm đường, khuấy đều",
      "Cho nước cốt dừa và một chút muối",
      "Đun sôi nhẹ rồi tắt bếp",
      "Ăn nóng hoặc để nguội",
    ],
    nutrition: {
      calories: 280,
      protein: 8,
      carbs: 52,
      fat: 6,
    },
    tags: ["tráng miệng", "ngọt", "truyền thống", "chè"],
  },
  {
    id: "8",
    name: "Bánh Xèo",
    description: "Bánh xèo giòn rụm với nhân tôm thịt, giá đỗ, ăn kèm rau sống",
    image: "/vietnamese-crispy-crepe-with-shrimp-and-bean-sprou.jpg",
    category: "món chính",
    cuisine: "Nam",
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: "Trung bình",
    ingredients: [
      { name: "Bột bánh xèo", amount: "300", unit: "g" },
      { name: "Tôm", amount: "300", unit: "g" },
      { name: "Thịt ba chỉ", amount: "200", unit: "g" },
      { name: "Giá đỗ", amount: "300", unit: "g" },
      { name: "Hành lá", amount: "1", unit: "bó" },
      { name: "Nước cốt dừa", amount: "100", unit: "ml" },
      { name: "Nghệ", amount: "1", unit: "thìa" },
    ],
    instructions: [
      "Pha bột bánh xèo với nước, nước cốt dừa, nghệ",
      "Ướp tôm và thịt với gia vị",
      "Đun nóng chảo, cho dầu",
      "Xào tôm thịt sơ qua",
      "Múc bột vào chảo, xoay đều",
      "Cho giá đỗ, hành lá lên bánh",
      "Đậy nắp cho bánh chín giòn",
      "Gấp đôi bánh, ăn kèm rau sống và nước mắm",
    ],
    nutrition: {
      calories: 380,
      protein: 24,
      carbs: 42,
      fat: 14,
    },
    tags: ["miền Nam", "giòn", "bữa trưa", "đặc sản"],
  },
]
